version: '3'

services: 
    visualization-service:
        build: ./
        command: yarn start
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        container_name: visualization-service

    nginx:
        image: nginx:alpine
        restart: on-failure
        container_name: nginx-service
        volumes:
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 8080:8080
        depends_on:
            - visualization-service
        